export const ROLES = {
    admin: {
        role: 'admin',
        displayName: 'Administrator',
        description: 'Full access to all features and workcenters',
        defaultWorkcenters: ['operations', 'production', 'security', 'workforce', 'vendors', 'sponsors', 'marketing', 'finance'],
        defaultPermissions: [
            { resource: 'tasks', action: 'create' },
            { resource: 'tasks', action: 'read' },
            { resource: 'tasks', action: 'update' },
            { resource: 'tasks', action: 'delete' },
            { resource: 'venue_features', action: 'create' },
            { resource: 'venue_features', action: 'read' },
            { resource: 'venue_features', action: 'update' },
            { resource: 'venue_features', action: 'delete' },
            { resource: 'events', action: 'create' },
            { resource: 'events', action: 'read' },
            { resource: 'events', action: 'update' },
            { resource: 'events', action: 'delete' },
            { resource: 'users', action: 'create' },
            { resource: 'users', action: 'read' },
            { resource: 'users', action: 'update' },
            { resource: 'users', action: 'delete' },
            { resource: 'integrations', action: 'create' },
            { resource: 'integrations', action: 'read' },
            { resource: 'integrations', action: 'update' },
            { resource: 'integrations', action: 'delete' },
        ],
    },
    operations_lead: {
        role: 'operations_lead',
        displayName: 'Operations Lead',
        description: 'Manage operations workcenter with read access to others',
        defaultWorkcenters: ['operations'],
        defaultPermissions: [
            { resource: 'tasks', action: 'create', workcenter: 'operations' },
            { resource: 'tasks', action: 'read' },
            { resource: 'tasks', action: 'update', workcenter: 'operations' },
            { resource: 'tasks', action: 'delete', workcenter: 'operations' },
            { resource: 'venue_features', action: 'read' },
            { resource: 'venue_features', action: 'update', workcenter: 'operations' },
            { resource: 'events', action: 'read' },
        ],
    },
    production_lead: {
        role: 'production_lead',
        displayName: 'Production Lead',
        description: 'Manage production workcenter with read access to others',
        defaultWorkcenters: ['production'],
        defaultPermissions: [
            { resource: 'tasks', action: 'create', workcenter: 'production' },
            { resource: 'tasks', action: 'read' },
            { resource: 'tasks', action: 'update', workcenter: 'production' },
            { resource: 'tasks', action: 'delete', workcenter: 'production' },
            { resource: 'venue_features', action: 'read' },
            { resource: 'venue_features', action: 'update', workcenter: 'production' },
            { resource: 'events', action: 'read' },
        ],
    },
    security_lead: {
        role: 'security_lead',
        displayName: 'Security Lead',
        description: 'Manage security workcenter with read access to others',
        defaultWorkcenters: ['security'],
        defaultPermissions: [
            { resource: 'tasks', action: 'create', workcenter: 'security' },
            { resource: 'tasks', action: 'read' },
            { resource: 'tasks', action: 'update', workcenter: 'security' },
            { resource: 'tasks', action: 'delete', workcenter: 'security' },
            { resource: 'venue_features', action: 'read' },
            { resource: 'venue_features', action: 'update', workcenter: 'security' },
            { resource: 'events', action: 'read' },
        ],
    },
    workforce_lead: {
        role: 'workforce_lead',
        displayName: 'Workforce Lead',
        description: 'Manage workforce workcenter with read access to others',
        defaultWorkcenters: ['workforce'],
        defaultPermissions: [
            { resource: 'tasks', action: 'create', workcenter: 'workforce' },
            { resource: 'tasks', action: 'read' },
            { resource: 'tasks', action: 'update', workcenter: 'workforce' },
            { resource: 'tasks', action: 'delete', workcenter: 'workforce' },
            { resource: 'venue_features', action: 'read' },
            { resource: 'venue_features', action: 'update', workcenter: 'workforce' },
            { resource: 'events', action: 'read' },
        ],
    },
    vendor_lead: {
        role: 'vendor_lead',
        displayName: 'Vendor Lead',
        description: 'Manage vendors workcenter with read access to others',
        defaultWorkcenters: ['vendors'],
        defaultPermissions: [
            { resource: 'tasks', action: 'create', workcenter: 'vendors' },
            { resource: 'tasks', action: 'read' },
            { resource: 'tasks', action: 'update', workcenter: 'vendors' },
            { resource: 'tasks', action: 'delete', workcenter: 'vendors' },
            { resource: 'venue_features', action: 'read' },
            { resource: 'venue_features', action: 'update', workcenter: 'vendors' },
            { resource: 'events', action: 'read' },
        ],
    },
    sponsor_lead: {
        role: 'sponsor_lead',
        displayName: 'Sponsor Lead',
        description: 'Manage sponsors workcenter with read access to others',
        defaultWorkcenters: ['sponsors'],
        defaultPermissions: [
            { resource: 'tasks', action: 'create', workcenter: 'sponsors' },
            { resource: 'tasks', action: 'read' },
            { resource: 'tasks', action: 'update', workcenter: 'sponsors' },
            { resource: 'tasks', action: 'delete', workcenter: 'sponsors' },
            { resource: 'venue_features', action: 'read' },
            { resource: 'venue_features', action: 'update', workcenter: 'sponsors' },
            { resource: 'events', action: 'read' },
        ],
    },
    marketing_lead: {
        role: 'marketing_lead',
        displayName: 'Marketing Lead',
        description: 'Manage marketing workcenter with read access to others',
        defaultWorkcenters: ['marketing'],
        defaultPermissions: [
            { resource: 'tasks', action: 'create', workcenter: 'marketing' },
            { resource: 'tasks', action: 'read' },
            { resource: 'tasks', action: 'update', workcenter: 'marketing' },
            { resource: 'tasks', action: 'delete', workcenter: 'marketing' },
            { resource: 'venue_features', action: 'read' },
            { resource: 'venue_features', action: 'update', workcenter: 'marketing' },
            { resource: 'events', action: 'read' },
        ],
    },
    finance_lead: {
        role: 'finance_lead',
        displayName: 'Finance Lead',
        description: 'Manage finance workcenter with read access to others',
        defaultWorkcenters: ['finance'],
        defaultPermissions: [
            { resource: 'tasks', action: 'create', workcenter: 'finance' },
            { resource: 'tasks', action: 'read' },
            { resource: 'tasks', action: 'update', workcenter: 'finance' },
            { resource: 'tasks', action: 'delete', workcenter: 'finance' },
            { resource: 'venue_features', action: 'read' },
            { resource: 'venue_features', action: 'update', workcenter: 'finance' },
            { resource: 'events', action: 'read' },
        ],
    },
    viewer: {
        role: 'viewer',
        displayName: 'Viewer',
        description: 'Read-only access to assigned workcenters',
        defaultWorkcenters: [],
        defaultPermissions: [
            { resource: 'tasks', action: 'read' },
            { resource: 'venue_features', action: 'read' },
            { resource: 'events', action: 'read' },
        ],
    },
};
//# sourceMappingURL=roles.js.map